services:
  db:
    image: postgres:17
    container_name: workouts_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: workouts_db
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d workouts_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./workouts_udec_backend
    container_name: workouts_backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: workouts_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network 
      - frontend_network
    volumes:
      - ./workouts_udec_backend/alembic:/app/alembic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  frontend:
    build:
      context: ./workouts_udec_frontend
    container_name: workouts_udec_frontend
    ports:
      - "4173:4173"
    networks:
      - frontend_network
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api
      - VITE_APP_TITLE=Workout Tracker
      - VITE_APP_VERSION=0.1.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3

  newman:
    image: postman/newman:alpine
    container_name: api_tests
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - backend_network
    volumes:
      - ./tests/postman:/etc/newman
    command: >
      run Endpoints-Casos-positivos.postman_collection.json -e Workout-API-Positivo.postman_environment.json
      --env-var base_url=http://backend:8000
      --reporters=cli
      --timeout-request=20000
    restart: "no"

volumes:
  postgres_data:
networks:
  backend_network:
    driver: bridge

  frontend_network:
    driver: bridge
